### PR TITLE
warn to unix users that the latest preview of ide will not launch reactlog

### PR DESCRIPTION
**Pull request by schloerke**
Displays a message to unix users on IDE preview v1.2.1303 that they keybindings will not work and to install the daily build.

The try statement is used as to avoid a dep on `rstudioapi` and just call the function that is in the namespace `tools:rstudio`.  This is near the top of the search path, so it should be found without directly stating the namespace name.

### CODE REVIEW

**Comment by jcheng5** [comment]
Is it literally that single build that doesn't work?

**Comment by schloerke** [comment]
@jcheng5 

@cpsievert  states that the daily build works on ubuntu, but found no issues with the latest preview release.

IDE Issue fixed: https://github.com/rstudio/rstudio/issues/4045 . This issue has nothing in particular to do with Unix

**Comment by schloerke** [comment]
* double checking on my vm

**Comment by schloerke** [comment]
What Carson found in the unix ide preview release



Since this was a marked preview release, we could support it.  Or we could ignore it completely with the stance that it's a preview release (which could have bugs) and will be updated within a month.

**Comment by schloerke** [comment]
@cpsievert I can not repro on Ubuntu 18 preview build (1.2.1303).  It works as expected for me when running app 007.

False positive?

screen shot 2019-03-05 at 10 41 43 pm
screen shot 2019-03-05 at 10 42 59 pm

**Comment by cpsievert** [comment]
@schloerke the issue surfaces with stable release (1.1.463), not preview, so I would do:

```
if (RStudio.Version()$version == "1.1.463") {
          packageStartupMessage(
            "Reactlog doesn't render properly in v1.1.463 RStudio's viewer.",
            " Please consider using another browser to view reactlog or ",
            " install the preview release of RStudio.\n",
            " https://www.rstudio.com/products/rstudio/download/preview/"
          )
 } 
```

**Comment by cpsievert** [comment]
As for https://github.com/rstudio/reactlog/pull/21#issuecomment-469956455, I'll double-check -- I have, in general, been seeing weird system errors on some of my ubuntu vms

**Comment by cpsievert** [comment]
I just reproduced from a fresh vm (Ubuntu 16.04, R 3.2.3, with RStudio 1.1.463)...I think this is a real thing

**Comment by schloerke** [comment]
closing this PR as it is fixed in #25

**Pull request closed without merging**
